apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    KafkaReadTopic=route.new-direction
    KafkaProduceTopic=route.new-position
    KafkaBootstrapServers=pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    KafkaConsumerGroupId=simulator
    security.protocol="SASL_SSL"
    sasl.mechanisms="PLAIN"
    sasl.username="575OEXRERUFUK662"
    sasl.password="a1hWtG1th0tfoFxDZGUBiDyHGx7zEwnd7e+Tn2onyvwQv8tl7KJg21vx19TcOjd8"